parameters:
    request_injector.class:                      Geonaute\LinkdataBundle\Injector\RequestInjector
    locale_injector.class:                       Geonaute\LinkdataBundle\Injector\LocaleInjector   
    geonaute_linkdata.auth_plugin.class:         Geonaute\LinkdataBundle\Plugin\AuthPlugin
    geonaute_linkdata.language_plugin.class:     Geonaute\LinkdataBundle\Plugin\LanguagePlugin
    geonaute_linkdata.result_cache_plugin.class: Geonaute\LinkdataBundle\Plugin\ResultCachePlugin
    geonaute_linkdata.formatter.class:           Geonaute\LinkdataBundle\Formatter\FormatterManager
    linkdata.datatype.utils.class:               Geonaute\LinkdataBundle\Utils\Datatype
    geonaute_linkdata.client.class:              %guzzle.client.class%

services:
    # Utils
    geonaute_linkdata.formatter:
        class: %geonaute_linkdata.formatter.class%
        arguments: [ @translator ]
        
    geonaute_linkdata.datatype.utils:
        class: %linkdata.datatype.utils.class%
        arguments: [ @geonaute_linkdata.formatter ]

    #Type 
    geonaute_linkdata.type.linkdata_choice:
        class: Geonaute\LinkdataBundle\Form\Type\LinkdataChoiceType
        calls: 
            - [setClient, [ @linkdata_rest_client ]]
        tags:
            - { name: form.type, alias: linkdata_choice }
            
    geonaute_linkdata.type.filter_linkdata_choice:
        class: Geonaute\LinkdataBundle\Form\Type\FilterLinkdataChoiceType
        calls: 
            - [setClient, [ @linkdata_rest_client ]]
        tags:
            - { name: form.type, alias: filter_linkdata_choice }
        
    # Rest client
    geonaute_linkdata.client:
        class: %geonaute_linkdata.client.class%
        tags:
            - { name: guzzle.client }
        calls:
            - [ setBaseUrl,       [ %linkdata_rest_client.base_url% ] ]
            - [ setDefaultOption, [ 'params/cache.override_ttl', 3600 ] ]
            - [ setDescription,   [ @geonaute_linkdata.service_description ] ]
            - [ addSubscriber,    [ @geonaute_linkdata.cache.memcache ] ]
            - [ addSubscriber,    [ @geonaute_linkdata.auth_plugin ] ]
            - [ addSubscriber,    [ @geonaute_linkdata.language_plugin ] ]
            - [ addSubscriber,    [ @geonaute_linkdata.result_cache_plugin ] ]
    linkdata_rest_client:
        alias: geonaute_linkdata.client

    geonaute_linkdata.service_description:
        class: %guzzle.service_description.class%
        factory_class: %guzzle.service_description.class%
        factory_method: factory
        arguments: [ %geonaute_linkdata.service_description.config_path% ]

    geonaute_linkdata.auth_plugin:
        class: %geonaute_linkdata.auth_plugin.class%
        arguments: [ @security.context, @request_injector ]

    geonaute_linkdata.language_plugin:
        class: %geonaute_linkdata.language_plugin.class%
        arguments: [ @locale_injector ]

    geonaute_linkdata.result_cache_plugin:
        class: %geonaute_linkdata.result_cache_plugin.class%

    request_injector:
        class: %request_injector.class%
        arguments: [ @service_container ]
        
    locale_injector:
        class: %locale_injector.class%
        arguments: [ @service_container ]        
        
    # cache
    geonaute_linkdata.cache.doctrine_cache_adapter:
        class: %guzzle.cache.doctrine.class%
        arguments: [ @doctrine.orm.default_result_cache ]
    geonaute_linkdata.cache.doctrine_cache_storage:
        class: Guzzle\Plugin\Cache\DefaultCacheStorage
        arguments: [ @geonaute_linkdata.cache.doctrine_cache_adapter ]
    geonaute_linkdata.cache.can_cache_strategy:
        class: Geonaute\LinkdataBundle\Plugin\CanCacheStrategy
        
    geonaute_linkdata.cache.memcache:
        class: %guzzle.plugin.cache.class%
        arguments: [ { storage: @geonaute_linkdata.cache.doctrine_cache_storage, can_cache: @geonaute_linkdata.cache.can_cache_strategy } ]