language: php

php:
  - 5.5
  - 5.6
  - 7.0

matrix:
  allow_failures:
    - php: 7.0

before_script:
    - SYMFONY_ENV=test composer install -n --prefer-source --no-suggest --no-progress

script: 
    - phpunit
